'use client'

import { Metadata } from "next"
import { useEffect, useState } from "react";
import { getAllPosts } from "@/services/getPost";
import LoadingPost from "./loading";
import Posts from "@/components/Posts";
import PostSearch from "@/components/PostSearch";

export const metadata: Metadata = {
  title: 'Blog | Learning Next',
  description: 'Generated by create next app',
}

export default  function Blog() {
    const [posts, setPosts] = useState<any[]> ([])
    const [loading, setLoading] = useState(true)

    useEffect(() => {
      getAllPosts()
      .then(setPosts)
      .then(() => {setLoading(false)})
    }, [])

    return (
      <>
        <h1>Blog page</h1>
        <PostSearch onSearch={setPosts}/>
        {loading ? <LoadingPost /> : <Posts posts={posts}/>}
      </>
    )
  }
  
  