'use client';

import { TheHeader } from '@/components/TheHeader'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { TheFooter } from '@/components/TheFooter'
import { ColorModeScript } from '@chakra-ui/react'
import theme from '@/theme'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Learning Next',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ColorModeScript initialColorMode={theme.config.initialColorMode}/>
        <TheHeader />
          {children}
        <TheFooter />
      </body>
    </html>
  )
}
