import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Home | Learning Next',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <h1>Welcome to NextTs world</h1>
  )
}
